include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    - annotate_redeclares
    - avoid_classes_with_only_static_members
    - avoid_types_on_closure_parameters
    - missing_code_block_language_in_doc_comment
    - type_literal_in_constant_pattern
    - unnecessary_library_name
    - unnecessary_null_aware_operator_on_extension_on_nullable

analyzer:
  errors:
    # Style decisions
    always_use_package_imports: ignore
    sort_constructors_first: ignore
