import 'accidental_test.dart' as accidental_test;
import 'cent_test.dart' as cent_test;
import 'chord_pattern_test.dart' as chord_pattern_test;
import 'chord_test.dart' as chord_test;
import 'closest_pitch_test.dart' as closest_pitch_test;
import 'equal_temperament_test.dart' as equal_temperament_test;
import 'frequency_test.dart' as frequency_test;
import 'harmonic_function_test.dart' as harmonic_function_test;
import 'hearing_range_test.dart' as hearing_range_test;
import 'interval_class_test.dart' as interval_class_test;
import 'interval_test.dart' as interval_test;
import 'just_intonation_test.dart' as just_intonation_test;
import 'key_signature_test.dart' as key_signature_test;
import 'key_test.dart' as key_test;
import 'mode_test.dart' as mode_test;
import 'notation_system_test.dart' as notation_system_test;
import 'note_name_test.dart' as note_name_test;
import 'note_test.dart' as note_test;
import 'pitch_class_test.dart' as pitch_class_test;
import 'pitch_test.dart' as pitch_test;
import 'quality_test.dart' as quality_test;
import 'scalable_test.dart' as scalable_test;
import 'scale_degree_test.dart' as scale_degree_test;
import 'scale_pattern_test.dart' as scale_pattern_test;
import 'scale_test.dart' as scale_test;
import 'size_test.dart' as size_test;
import 'tuning_fork_test.dart' as tuning_fork_test;

void main() {
  accidental_test.main();
  cent_test.main();
  chord_pattern_test.main();
  chord_test.main();
  closest_pitch_test.main();
  equal_temperament_test.main();
  frequency_test.main();
  harmonic_function_test.main();
  hearing_range_test.main();
  interval_class_test.main();
  interval_test.main();
  just_intonation_test.main();
  key_signature_test.main();
  key_test.main();
  mode_test.main();
  notation_system_test.main();
  note_name_test.main();
  note_test.main();
  pitch_class_test.main();
  pitch_test.main();
  quality_test.main();
  scalable_test.main();
  scale_degree_test.main();
  scale_pattern_test.main();
  scale_test.main();
  size_test.main();
  tuning_fork_test.main();
}
